export const NEWS_HISTORY_FILE = "news-history.json";

export const query = [
  '"software development"',
  '"developer tools"',
  '"frontend development"',
  '"backend development"',
  '"web framework"',
  "openai",
  "chatgpt",
  "anthropic",
  "claude",
  "deepseek",
  "grok",
  "react",
  '"next.js"',
  "vue",
  "angular",
  '"node.js"',
  "express",
  "nestjs",
  "fastapi",
  "django",
  '"spring boot"',
  "rust",
  "golang",
].join(" OR ");

export const domains = [
  "techcrunch.com",
  "theverge.com",
  "arstechnica.com",
  "venturebeat.com",
  "thenewstack.io",
  "infoq.com",
  "wired.com",
  "github.blog",
].join(",");

export const keywords = [
  "software",
  "developer",
  "frontend",
  "backend",
  "framework",
  "javascript",
  "typescript",
  "react",
  "next.js",
  "vue",
  "angular",
  "node",
  "express",
  "nestjs",
  "fastapi",
  "django",
  "spring",
  "rust",
  "golang",
  "openai",
  "chatgpt",
  "anthropic",
  "claude",
  "deepseek",
  "grok",
  "ai coding",
  "developer tools",
];
